# .github/workflows/ci.yml
name: Vite CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run linter (optional, only if lint script exists)
      - name: Run lint
        run: npm run lint --if-present

      # Build project with Vite
      - name: Build project
        run: npm run build
