name: Fullstack CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install --legacy-peer-deps

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps --prefix frontend

      # ✅ Verify frontend build (if you add "build" script later)
      - name: Verify frontend build
        run: npm run build --prefix frontend --if-present
